### ISSUE TITLE
Typo in the FAQ page

### ISSUE THREAD

**Issue by TaoSc** [dolphin-emu/www#101]
I have absolutely no idea if this is the right place to post this but it should at least get noticed here.

There’s a small typo in the answer here: https://dolphin-emu.org/docs/faq/#how-much-ram-do-i-need-run-dolphin

It should be “has no effect on […]” instead of “has no affect on […]”.

Sorry if I should have posted this somewhere else. I looked at the CONTRIBUTING.md file but it didn’t help me much and quickly glancing over the code proved unsuccessful too.

**Comment by delroth** [comment]
@JMC47

**Comment by JMC47** [comment]
Fixed, thank you!
