### ISSUE TITLE
Invalid certificate in Brazilian version of the website

### ISSUE THREAD

**Issue by thomasbbrunner** [dolphin-emu/www#109]
When accessing the Brazilian version of the Dolphin website (redirected from a Google search), there is an invalid certificate warning.

Only happens when accessing the website with the domain preceded by *'www'*. (https://www.br.dolphin-emu.org/)

Tested on Chrome for Linux (latest version).

**Comment by delroth** [comment]
Yes, that's expected. www.br.dolphin-emu.org is not a valid domain to
access our website, and we don't use that URL anywhere. Not sure how you
ended up with a www.
