### ISSUE TITLE
downloads page should clearly mark "beta track" versions

### ISSUE THREAD

**Issue by ashkitten** [dolphin-emu/www#116]
various distro packages (nix, ubuntu ppa, flatpak, etc) seem to have varying ideas of which version actually corresponds to a progress report. it's currently very difficult for a human to find out which version that is, since the only way to obtain the definitive answer is via the api

being uncoordinated like this causes issues with trying to coordinate netplay across various distros, so it'd be really nice to clearly mark for humans the definitive "beta track" version on the downloads page so every packager has an easy time finding the correct one

**Comment by delroth** [comment]
Done: https://dolphin-emu.org/download/#download-beta
