### ISSUE TITLE
False Japanes text

### ISSUE THREAD

**Issue by ghost** [dolphin-emu/www#118]
Inazuma eleven strikers
The text (furigana) not matching the kanji , i put 3 different  text from other conversation in a single pic....

![rrr](https://user-images.githubusercontent.com/64847752/82693296-36955480-9c59-11ea-8181-a3b524701200.PNG)

**Comment by JosJuice** [comment]
Problems with the emulator should be reported at https://bugs.dolphin-emu.org/projects/emulator, not here.
