### ISSUE TITLE
Accessibility in the main UI

### ISSUE THREAD

**Issue by RealAmethyst** [dolphin-emu/www#121]
Hi I am Gamulation. I am blind and uses dolphin on a dayly bases.
As of dolphin 5.0 11655 the interface is no longer accessible.
I can still navigate all the menus, but without speach. That's not very good. I uses a screen reader to navigate the interface of Dolphin as well as the hole windows.
I have tryde to move all the QT librarrys into the new dolphin version, but it doesn't work.
Can we fix this? 
Let's all play equally.

**Comment by JosJuice** [comment]
This is the issue tracker for the website, not for Dolphin itself. There is already an open issue about this at the Dolphin issue tracker: https://bugs.dolphin-emu.org/issues/12014.

**Comment by RealAmethyst** [comment]
oh. Shit. Should I close this then?
