### ISSUE TITLE
Be clearer on downloads page that the "stable versions" are really far behind in features

### ISSUE THREAD

**Issue by TheHarmonicRealm** [dolphin-emu/www#126]
When I first got the emulator, I downloaded the stable version 5.0, because [the weakly-worded description of the stable versions](https://dolphin-emu.org/download/) made it sound like what most people should do:

> Stable versions are released after a lot of testing to ensure emulation performance and stability. However, since they are released less often, they might be outdated and lacking some new features.

Sounds like what every new user should get, right? It makes it sound like it would be worth it to have a stable, but not quite up to date version. But when I used it, I found a lot of super important things aren't in 5.0, such as support for the very efficient RVZ format. I think the description of the stable releases on the downloads page should make it a lot clearer that the "stable version" is very behind in some major features, and that most people should get the beta versions.

**Comment by OatmealDome** [comment]
Stable has been retired!
