### ISSUE TITLE
cheat manager

### ISSUE THREAD

**Issue by manaboy** [dolphin-emu/www#144]
Hi all, so Gecko website has been down for some time now, the owner said his going to close down the site, he said all the codes will be still available but from gcforever, or something like that, why hasn't the download link on dolphin been updated?

**Comment by manaboy** [comment]
Please update the download link for codes to https://web.archive.org/web/20191001120556/https://www.geckocodes.org/index.php?chid=R&r=*&l=m

**Comment by JosJuice** [comment]
We updated the URL in Dolphin a year and a half ago. See https://github.com/dolphin-emu/dolphin/pull/9133.
