### ISSUE TITLE
DOCS: Out Of Date Visual C++ Redistributable Link

### ISSUE THREAD

**Issue by PatrickFerry** [dolphin-emu/www#155]
The docs which serve the FAQ contains an link to the outdated Visual C++ Redistributable for VS16(2019) rather than VS17(2022)

This can be seen in the following page, in an anchor for the "direct link":
https://dolphin-emu.org/docs/faq/#program-cant-start-because-vcdll-is-missing

As far as I know this text is within a DB so I can't change it myself

**Comment by OatmealDome** [comment]
Updated, thanks!
