### ISSUE TITLE
Question: netplay server hosted and source code

### ISSUE THREAD

**Issue by luc-git** [dolphin-emu/www#157]
Hello I have a question. Where is the netplay server hosted and why is the server source code not available?

**Comment by JosJuice** [comment]
The index server is here: https://github.com/dolphin-emu/netplay-index

The traversal server is here: https://github.com/dolphin-emu/dolphin/blob/b71fdef356caf6ca376c0df474212a192951e810/Source/Core/Common/CMakeLists.txt#L333

The URLs we host these servers at are listed here: https://github.com/dolphin-emu/dolphin/blob/b71fdef356caf6ca376c0df474212a192951e810/Source/Core/Core/Config/NetplaySettings.cpp#L16-L23
