### ISSUE TITLE
Wii sports joy-con detection inverted

### ISSUE THREAD

**Issue by Papotheos** [dolphin-emu/www#159]
I downloaded BetterJoyForCemu to play Wii games with my joy-cons and configured my controls and buttons using a youtube tutorial. When I started Wii sports the controls were inverted. I reckon that's because if you take a look at a right joy-con the IR camera is at the bottom, which on the wii remote is on the top side so all my gyro controls are backwards. Is there a way to config that using Dolphin Emulator or BetterJoy settings?
(Sorry if I type bad English. It's not my first language.)

**Comment by JosJuice** [comment]
This issue tracker is for bugs in the code of the Dolphin website. If you need help configuring controllers, please ask in the forums, Discord server, or IRC.

**Comment by Papotheos** [comment]
where can I find the forums?

**Comment by JosJuice** [comment]
https://forums.dolphin-emu.org/
