### ISSUE TITLE
Hori wireless gamecube controller for switch support

### ISSUE THREAD

**Issue by ApostolosRisen** [dolphin-emu/www#164]
Dolphin detects the controller when plugged in via cable but registers zero inputs at all with the latest version, possibly a controller side issue as it registers as wireless and may be that it can only be used as such. But any information you may have or be able to speculate beyond that would be great

**Comment by JosJuice** [comment]
This issue tracker is for the website. The issue tracker for the emulator is at https://bugs.dolphin-emu.org/projects/emulator

Also, "any information you may have or be able to speculate beyond that would be great" sounds more like a support request than a issue report. For support, please use the forums, Discord or IRC.
