### ISSUE TITLE
Bad design on 500

### ISSUE THREAD

**Issue by gustavi** [dolphin-emu/www#24]
The design is wrong in the 500 page (http://i.imgur.com/BbSlXOp.png) and links are broken (http://paste.awesom.eu/jrI3).

**Comment by delroth** [comment]
What's wrong about the design?

Links being broken: agreed, not sure how to fix that (maybe changing the priority of context processors). This is an edge case I'm not too interested in fixing, I'll be happy to review PRs.

**Comment by Zopieux** [comment]
The only design flaw I can notice is the empty dropdown on the right.

**Comment by gustavi** [comment]
To be honest, I have no idea what was wrong.
