### ISSUE TITLE
Ability to link to different sections of articles

### ISSUE THREAD

**Issue by JMC47** [dolphin-emu/www#28]
Something that'd be useful when trying to explain features to users would be able to link to different sections of the articles.  When someone asks a question about a particular new feature or fixed bug, when we could link them directly to the part of the progress report that talks about it.

This has been requested a few times by people on top of this, but I don't remember their reasonings for wanting it.

**Comment by Zopieux** [comment]
For Markdown it should be enough to enable [the `toc` extension](https://pythonhosted.org/Markdown/extensions/toc.html), to add `id` attributes on headers. 

I'm not sure about RestructuredText though, maybe there is a similar plugin or it's builtin.

**Comment by Zopieux** [comment]
[Merged](https://github.com/Fantomas42/django-blog-zinnia/pull/406) upstream! So now this could be used in Dolphin.

**Comment by Zopieux** [comment]
Workaround by @delroth started in 418106637ac293b03e89cfa853df208cf24017c5.
