### ISSUE TITLE
Download button is too long for mobile devices

### ISSUE THREAD

**Issue by MaJoRoesch** [dolphin-emu/www#31]
On mobile devices or anything with a narrow window, the download button's text is too long, making the button extend to the right of the screen.

Perhaps the site could detect when the screen is too narrow and switching the text to "Download" or maybe just "Download Dolphin 4.0-xxxx" or something? Or us when the hamburger menu appears as the trigger for less text here? #notacoder

From my iPhone 4S:

![img_0033](https://cloud.githubusercontent.com/assets/6551020/6840938/fb6b1d18-d34f-11e4-861f-05da437ce0cd.PNG)

**Comment by Zopieux** [comment]
We could either:
- allow the button text to wrap
- force a line break after *Download Dolphin* and put the remaining detailed info on another line, with a smaller font size (and also allow wrapping actually)
