### ISSUE TITLE
Dolphin keeps crashing

### ISSUE THREAD

**Issue by TheLukeGuy** [dolphin-emu/www#32]
Dolphin keeps crashing when I try using the Animal Crossing: City Folk .iso file... It really annoys me and I really want to play it. I don't have a Wii, so I can't play it on there.

**Comment by Zopieux** [comment]
This is a bug tracker for Dolphin Emu website (hence the project name `www`). Please report bugs on [Google Code issue tracker](https://code.google.com/p/dolphin-emu/issues/list).
