### ISSUE TITLE
.svgz files are not served with the proper “Content-Encoding: gzip” header

### ISSUE THREAD

**Issue by linkmauve** [dolphin-emu/www#34]
This prevents them from being displayed by browsers, as they get served a gzip file they don’t expect, instead of proper SVG.

Fixing that issue would allow compressed SVG files to be used in progress reports, and lower bandwidth usage.

**Comment by delroth** [comment]
What's the point of .svgz vs. just having the webserver do transparent gzip encoding on the files?

**Comment by linkmauve** [comment]
I just tested again, you are right, I correctly get gzipped data when I `curl -H 'Accept-Encoding: gzip'` some svg file.  I don’t know why it didn’t at the time I opened that issue, maybe I just didn’t test correctly.

Anyway, there is effectively no point in using svgz instead of compressing on the fly (aside from not having to compress it again and again, but it isn’t an issue), I’m closing this issue.
