### ISSUE TITLE
dolphin-emu.org has bad security settings

### ISSUE THREAD

**Issue by christianweinz** [dolphin-emu/www#41]
I disabled SSLv1 and SSLv2 and ciphers using RC4 and I couldn't connect to https://dolphin-emu.org anymore, forcing me to keep weak encryption on my system enabled.

There are more issues[1] that need fixing, too.

[1] https://www.ssllabs.com/ssltest/analyze.html?d=dolphin-emu.org

**Comment by christianweinz** [comment]
I meant TLSv1.0 and TLSv1.1 instead of SSLv1 and SSLv2.

**Comment by delroth** [comment]
We have no control over this.
