### ISSUE TITLE
New Issue Tracker URL on Download Page Is Incorrect

### ISSUE THREAD

**Issue by Pringo** [dolphin-emu/www#48]
Right now it links to: https://bugs.dolphin-emu.org/projects/redmine/issues which is presumably the issue tracker for the issue tracker itself and not for Dolphin.

I believe it should instead link to: https://bugs.dolphin-emu.org/projects/emulator/issues which is what the Dolphin GitHub page links to.

**Comment by Zopieux** [comment]
Duplicate of #49, already fixed in #46.

**Comment by delroth** [comment]
Not duplicate, and not fixed.

**Comment by Pringo** [comment]
Fixed in #51 and seems to be working on the site now. Thanks.
