### ISSUE TITLE
Issue Tracker Link in FAQ Needs to Be Updated

### ISSUE THREAD

**Issue by Pringo** [dolphin-emu/www#49]
https://dolphin-emu.org/docs/faq/

"If you find a bug in a game that isn't listed on the Wiki, please checkout the issue tracker..."

Link should be updated to: https://bugs.dolphin-emu.org/projects/emulator/issues

**Comment by Zopieux** [comment]
Should be already fixed in #46. Maybe its not pushed to production yet. cc @delroth

**Comment by delroth** [comment]
The FAQ data is dynamic and in DB. @JMC47 can fix it.

**Comment by JMC47** [comment]
Fixed.
