### ISSUE TITLE
Google Analytics TOS - No privacy policy on dolphin-emu.org

### ISSUE THREAD

**Issue by DXGLdotinfo** [dolphin-emu/www#57]
According to the Chrome extension Ghostery, your website uses a Google Analytics tracker.
According to section 7 of https://www.google.com/analytics/terms/us.html you are supposed to have a privacy policy on your site that specifically discloses the use of Google Analytics.

**Comment by cupofjoakim** [comment]
This'd be great over all, not just for the Google Analytics part. There should be a simple paragraph in these terms explaining that the user is responsible for his own actions and clarifying that Dolphin does not support piracy. This is already apparent in the FAQ, but having a collected TOS/TAC sure would be nice.

It wouldn't need to be anything big, basically a new text page with our terms and a little piece of text on the download page that says something like "By downloading Dolphin you're agreeing to the <link>terms and conditions</link>.".

The only big part of this is figuring out exactly what points would need to be in the TOS. I'm new to this project, so I'd guess there's some higher ups that would have awesome input. @delroth, do you know anything?

**Comment by delroth** [comment]
There's no way we're going to have ToS for usage of Dolphin. Feel free to
write a privacy policy we can put in the footer to make people feel better
if you want.

**Comment by WilliamFeely** [comment]
Actually the only T&C you can require for downloading must be compliant with the GPL license.
Piracy disclaimers are not a good idea; they can be an acknowledgement of liability.

**Comment by WilliamFeely** [comment]
If you don't have a privacy policy you have to remove the Google Analytics per their TOS.

**Comment by WilliamFeely** [comment]
Here is the privacy notice I put on my own website when I installed Google Analytics recently; go ahead and use it if you like:

=== Google Analytics ===
* This website uses Google Analytics to gather aggregated information regarding the use of this website.  No personal information is gathered at any time as a result of this software.  If you would like to opt out of Analytics tracking, you may go to https://tools.google.com/dlpage/gaoptout or alternatively you can install a third-party extension such as Ghostery at https://www.ghostery.com/our-solutions/ghostery-browser-extention/ (remember to pay attention to the settings and ensure "Google Analytics" is crossed out in the info box when visiting this site)
* For privacy information regarding Google Analytics, please visit https://support.google.com/analytics/answer/6004245?hl=en

**Comment by delroth** [comment]
Fixed by https://dolphin-emu.org/docs/privacy/
