### ISSUE TITLE
Blog RSS Feed

### ISSUE THREAD

**Issue by wertercatt** [dolphin-emu/www#65]
Please add a RSS feed for [The blog](http://www.dolphin-emu.org/blog), if the blog had a RSS feed it would be easier for people to keep up to date on the newest posts.

**Comment by delroth** [comment]
There is already an RSS feed for our blog.

**Comment by wertercatt** [comment]
Now that I've looked again, I've found it. I'll go ahead and mark this issue as closed.
Note for people in the future who are consulting this issue for information, the RSS feed is available at [this location](https://dolphin-emu.org/blog/feeds/)
