### ISSUE TITLE
AMD Ryzen chips

### ISSUE THREAD

**Issue by kukrimate** [dolphin-emu/www#80]
AMD Ryzen chips are out and they feature a much higher IPC yet the FAQ still bashes on AMD for having bad IPC and being much slower than Intel, but it's not true for the current gen.

**Comment by ThePeoplesKnee** [comment]
I think the bigger problem here is that the FAQ as a whole is heavily dated and focused more around the 4.0 era of Dolphin, where the emulator was the slowest it had ever been. I imagine CPU requirements for more demanding games have gone down drastically as well, so maybe it'd be worth mentioning more than just top of the line i7s and overclocked i5s from Q2 2013. More recent dual cores CPUs like most of the i3 lineup and the Kaby Lake Pentium chips are able to handle a lot of games very well.
