### ISSUE TITLE
Unclear Code License

### ISSUE THREAD

**Issue by wertercatt** [dolphin-emu/www#83]
```
Licensing
---------

Code is licensed under the MIT license: do whatever you want with it. Images
are licensed under the CC-by-sa license: if you want to use them, please
attribute them to us and redistribute them under the same license.
```
There are two licenses that are typically referred to as the "MIT license." These are the [Expat License](https://directory.fsf.org/wiki/License:Expat) and [X11 License](https://directory.fsf.org/wiki/License:X11). Please clarify which license this project's code is making use of, perhaps by committing it as a license.txt or license.md file.

**Comment by delroth** [comment]
I do mean the Expat one, will add a LICENSE file later when I'm back from work.

**Comment by Krutonium** [comment]
So it's been a while, is this ever actually going to happen?

**Comment by delroth** [comment]
Cleaned up in d3f652bd6d5121c0310a8205184cb89c417514dd.
