### ISSUE TITLE
Add da translation

### ISSUE THREAD

**Issue by scootergrisen** [dolphin-emu/www#87]
I dont see danish translation on https://dolphin-emu.org/ even though only two strings are untranslated in FAQ on Transifex.
So please add danish translation.
We have switched from using "da_DK" to "da" on Transifex so i suggest to do the same on https://github.com/dolphin-emu/www/tree/stable/dolweb/locale so there is only "da" and not "da_DK".

**Comment by delroth** [comment]
That's now done, sorry it took so long!
