### ISSUE TITLE
Pager of blog entires page is broken

### ISSUE THREAD

**Issue by mzji** [dolphin-emu/www#90]
The class name of pager's `ul` element is `paginator` :

![wrong](https://user-images.githubusercontent.com/23279426/43685203-51fb5cce-98e1-11e8-9b79-ca38b2c05955.png)

However, the correct class name should be `pager` :

![right](https://user-images.githubusercontent.com/23279426/43685207-67385362-98e1-11e8-9557-93ea38aa0505.png)

**Comment by delroth** [comment]
Fixed, thanks.
